import { IMAGES } from './images';

export interface ProgramData {
  slug: string;
  title: string;
  tagline: string;
  category: string;
  color: string;
  glyph: string;
  heroImg: string;
  galleryImgs: string[];
  duration: string;
  format: string;
  level: string;
  language: string;
  badge?: string;
  overview: string[];
  outcomes: string[];
  curriculum: { module: string; topics: string[] }[];
  whoFor: string[];
  faqs: { q: string; a: string }[];
  testimonial?: { quote: string; name: string; role: string; avatar: string };
}

export const PROGRAMS: Record<string, ProgramData> = {

  // ─── FLAGSHIP ────────────────────────────────────────────────
  personality: {
    slug: 'personality',
    title: 'Personality Development',
    tagline: 'Unlock unshakeable confidence, magnetic communication and emotional mastery.',
    category: 'Flagship Program',
    color: '#d4521a',
    glyph: '✦',
    heroImg: IMAGES.personality,
    galleryImgs: [IMAGES.heroStudents, IMAGES.teamCollab, IMAGES.blog3],
    duration: '8 Weeks',
    format: 'Online / Offline',
    level: 'All levels',
    language: 'English, Hindi, Marathi',
    badge: 'Most Popular',
    overview: [
      'The Personality Development program is IkigaiE\'s most transformative flagship offering. Over 8 structured weeks, you will dismantle self-limiting beliefs, build unshakeable confidence, and develop the communication presence that opens doors.',
      'Every session blends psychology, practical exercises, and peer feedback. You won\'t just learn theory — you will practise, reflect, and grow in real time with a cohort of motivated peers.',
      'Designed for students and professionals in India who feel held back by self-doubt, shyness, or unclear communication, this program has helped hundreds step fully into who they are meant to be.',
    ],
    outcomes: [
      'Speak with confidence in any room — boardrooms, classrooms, social settings',
      'Master body language, tone, and the art of first impressions',
      'Develop emotional intelligence: manage stress, empathy, and conflict',
      'Build a growth mindset that turns setbacks into stepping stones',
      'Create a personal brand that is authentic and compelling',
      'Lead conversations with clarity, energy, and purpose',
    ],
    curriculum: [
      { module: 'Module 1: Know Yourself', topics: ['Self-awareness assessment', 'Identifying limiting beliefs', 'Strengths & values mapping'] },
      { module: 'Module 2: The Confidence Code', topics: ['Psychology of confidence', 'Power posture & body language', 'Eliminating negative self-talk'] },
      { module: 'Module 3: Communication Mastery', topics: ['Vocal presence & tonality', 'Active listening techniques', 'Storytelling for impact'] },
      { module: 'Module 4: Emotional Intelligence', topics: ['Recognising & regulating emotions', 'Empathy in relationships', 'Conflict resolution frameworks'] },
      { module: 'Module 5: Social Presence', topics: ['Networking with authenticity', 'Small talk to deep conversations', 'Building lasting impressions'] },
      { module: 'Module 6: Personal Brand', topics: ['Defining your unique identity', 'Online & offline presence', 'Elevator pitch mastery'] },
      { module: 'Module 7: Leadership Mindset', topics: ['Taking ownership', 'Decision making under pressure', 'Inspiring others through action'] },
      { module: 'Module 8: Integration & Launch', topics: ['Personal brand presentation', 'Peer feedback sessions', 'Action plan for life beyond the program'] },
    ],
    whoFor: [
      'College students preparing for placements and interviews',
      'Early-career professionals feeling underconfident',
      'Anyone who struggles with shyness or social anxiety',
      'People who want to communicate with more clarity and power',
    ],
    faqs: [
      { q: 'Is this program online or offline?', a: 'Both options are available. Online sessions run live via Zoom twice a week. Offline batches are available in Mumbai and Pune.' },
      { q: 'How large are the batches?', a: 'We keep batches to a maximum of 20 participants to ensure personal attention and meaningful peer interaction.' },
      { q: 'Will I get a certificate?', a: 'Yes. Upon completing all 8 modules and the final presentation, you receive an IkigaiE certificate recognised by our corporate partners.' },
      { q: 'What if I miss a session?', a: 'All online sessions are recorded and shared within 24 hours. You can catch up at your own pace without falling behind.' },
    ],
    testimonial: { quote: 'I came in barely able to introduce myself. I left presenting in front of 200 people at our college fest. IkigaiE changed everything.', name: 'Riya Sharma', role: 'Engineering Student, Pune', avatar: IMAGES.avatar1 },
  },

  speaking: {
    slug: 'speaking',
    title: 'Public Speaking & Communication',
    tagline: 'Command any stage, win any room — from interviews to TEDx.',
    category: 'Flagship Program',
    color: '#3d8f52',
    glyph: '◆',
    heroImg: IMAGES.speaking,
    galleryImgs: [IMAGES.blog4, IMAGES.heroStudents, IMAGES.blog2],
    duration: '6 Weeks',
    format: 'Online / Offline',
    level: 'Beginner to Advanced',
    language: 'English, Hindi',
    badge: 'High Demand',
    overview: [
      'Public speaking is ranked the number one fear globally — yet it is also the single skill most correlated with career advancement. This 6-week intensive transforms you from hesitant to compelling.',
      'Through structured speech exercises, real-time feedback, and video analysis, you will develop a signature speaking style that is authentic, persuasive, and impossible to ignore.',
      'Whether you need to ace job interviews, lead team meetings, deliver college presentations, or take the stage at an event — this program equips you with the tools, technique, and mindset to do it brilliantly.',
    ],
    outcomes: [
      'Deliver speeches and presentations without fear or hesitation',
      'Structure arguments that persuade and inspire action',
      'Use vocal variety, pacing, and silence like a professional',
      'Handle Q&A sessions, debates, and unexpected questions confidently',
      'Develop a memorable on-stage presence and personal speaking style',
      'Succeed in GDs, interviews, pitches, and team presentations',
    ],
    curriculum: [
      { module: 'Week 1: Foundations', topics: ['Overcoming stage fright', 'The 3 pillars of great speaking', 'Ice-breaker speeches'] },
      { module: 'Week 2: Structure & Content', topics: ['The PREP framework', 'Storytelling techniques', 'Opening and closing with impact'] },
      { module: 'Week 3: Delivery & Voice', topics: ['Vocal projection & modulation', 'Pacing, pausing & emphasis', 'Breathing for speakers'] },
      { module: 'Week 4: Body Language', topics: ['Stage movement & gestures', 'Eye contact mastery', 'Removing filler words'] },
      { module: 'Week 5: Advanced Formats', topics: ['Persuasive speaking', 'Group discussions & debates', 'Impromptu speaking'] },
      { module: 'Week 6: Showcase', topics: ['Final 5-minute speech', 'Video review & feedback', 'Personal growth roadmap'] },
    ],
    whoFor: [
      'Students preparing for placements, GDs, and campus events',
      'Professionals who want to lead meetings and present confidently',
      'Entrepreneurs who need to pitch ideas and build authority',
      'Anyone who freezes or goes blank when speaking in public',
    ],
    faqs: [
      { q: 'Do I need any prior experience?', a: 'Absolutely not. We welcome complete beginners and tailor feedback to each participant\'s current level.' },
      { q: 'How many speeches will I give?', a: 'You will deliver at least 8 speeches across the program, receiving structured written and verbal feedback every time.' },
      { q: 'Is the program recorded?', a: 'Yes — your speeches are recorded so you can watch your own progress and identify specific areas to improve.' },
    ],
    testimonial: { quote: 'In week one I could barely look at the camera. By week six I was delivering a 5-minute speech to a live audience of 50. The transformation was real.', name: 'Arjun Mehta', role: 'MBA Student, Mumbai', avatar: IMAGES.avatar2 },
  },

  career: {
    slug: 'career',
    title: 'Career Counselling',
    tagline: 'Find your path, own your direction — expert 1-on-1 guidance for every crossroads.',
    category: 'Flagship Program',
    color: '#3670a8',
    glyph: '◉',
    heroImg: IMAGES.career,
    galleryImgs: [IMAGES.blog1, IMAGES.blog5, IMAGES.teamCollab],
    duration: '4 Sessions',
    format: '1-on-1 (Online / Offline)',
    level: 'All stages',
    language: 'English, Hindi, Marathi',
    overview: [
      'Career confusion is one of the most stressful experiences a person can face. Our Career Counselling program provides a structured, personalised journey to clarity — with a certified mentor dedicated entirely to you.',
      'Across four focused sessions, we use psychometric assessments, ikigai mapping, and career market research to help you understand not just what you can do — but what you should do, and why.',
      'Whether you are a student choosing between paths, a professional feeling stuck, or someone wanting to make a bold pivot, our counsellors have guided hundreds through similar crossroads.',
    ],
    outcomes: [
      'Crystal-clear understanding of your strengths, values, and interests',
      'A concrete, personalised career roadmap with short and long-term goals',
      'Confidence to make bold career decisions without second-guessing',
      'Interview preparation and personal branding strategies',
      'Awareness of high-growth career paths aligned to your ikigai',
      'An ongoing mentor relationship for support beyond the sessions',
    ],
    curriculum: [
      { module: 'Session 1: Discovery', topics: ['Psychometric assessment review', 'Ikigai mapping exercise', 'Understanding your values & non-negotiables'] },
      { module: 'Session 2: Exploration', topics: ['Career path mapping', 'Researching aligned opportunities', 'Skills gap analysis'] },
      { module: 'Session 3: Strategy', topics: ['Building your personal roadmap', 'Resume & LinkedIn review', 'Interview & networking strategy'] },
      { module: 'Session 4: Action', topics: ['90-day action plan', 'Accountability systems', 'Open Q&A and next steps'] },
    ],
    whoFor: [
      'Students uncertain about which field or college to choose',
      'Fresh graduates confused about their first job',
      'Mid-career professionals wanting to change domains',
      'Anyone feeling stuck, unfulfilled, or directionless in their career',
    ],
    faqs: [
      { q: 'Who are the counsellors?', a: 'All our counsellors are certified career coaches with 5+ years of experience in their respective domains. You are matched based on your background and goals.' },
      { q: 'Can I buy more sessions?', a: 'Yes. Many clients continue beyond the initial 4 sessions. Additional sessions can be purchased at a discounted rate.' },
      { q: 'Is my information confidential?', a: 'Completely. Everything discussed with your counsellor is strictly confidential and never shared without your consent.' },
    ],
    testimonial: { quote: 'I was about to accept a job I hated just to please my parents. Three sessions in, I had the clarity and the courage to choose a completely different path. Best investment I ever made.', name: 'Priya Patel', role: 'UX Designer, Bangalore', avatar: IMAGES.avatar3 },
  },

  leadership: {
    slug: 'leadership',
    title: 'Leadership & Team Building',
    tagline: 'Develop the mindset, skills, and presence of a true leader.',
    category: 'Flagship Program',
    color: '#c9a84c',
    glyph: '★',
    heroImg: IMAGES.leadership,
    galleryImgs: [IMAGES.aboutHero, IMAGES.blog3, IMAGES.office],
    duration: '6 Weeks',
    format: 'Group / Corporate',
    level: 'Mid to Senior',
    language: 'English, Hindi',
    overview: [
      'Great leaders are not born — they are built through intentional practice, honest feedback, and the right frameworks. This 6-week program is designed for emerging and existing leaders who want to amplify their impact.',
      'From managing difficult conversations to building high-performance teams, every module equips you with both the theory and the practical tools to lead with confidence, empathy, and strategic vision.',
      'The program also includes a corporate stream for organisations looking to develop leadership pipelines across their teams.',
    ],
    outcomes: [
      'Lead with clarity, purpose, and authentic confidence',
      'Build and manage high-performance, cohesive teams',
      'Master difficult conversations, conflict resolution, and feedback',
      'Develop strategic thinking and decision-making under pressure',
      'Create a culture of accountability, trust, and motivation',
      'Build your leadership identity and executive presence',
    ],
    curriculum: [
      { module: 'Week 1: Leadership Identity', topics: ['What kind of leader are you?', 'Core values & leadership philosophy', 'Self-awareness as a superpower'] },
      { module: 'Week 2: Communication', topics: ['Directness with empathy', 'Active listening for leaders', 'Giving & receiving feedback'] },
      { module: 'Week 3: Team Dynamics', topics: ['Building trust in teams', 'Understanding team personalities', 'Delegation and ownership'] },
      { module: 'Week 4: Conflict & Pressure', topics: ['Navigating difficult conversations', 'Decision-making frameworks', 'Leading through uncertainty'] },
      { module: 'Week 5: Culture & Motivation', topics: ['Building a high-performance culture', 'Intrinsic motivation techniques', 'Recognition and accountability'] },
      { module: 'Week 6: Vision & Impact', topics: ['Communicating a compelling vision', 'Influence without authority', 'Your leadership legacy'] },
    ],
    whoFor: [
      'Team leads, managers, and department heads',
      'Entrepreneurs building and scaling teams',
      'Corporate HR teams developing leadership pipelines',
      'Students in leadership positions at colleges and organisations',
    ],
    faqs: [
      { q: 'Is there a corporate version of this program?', a: 'Yes. We offer custom corporate batches where the program is tailored to your organisation\'s values, challenges, and goals.' },
      { q: 'Can individuals join or only teams?', a: 'Both. Individuals can join our open batches, while corporate clients can book private cohorts for their teams.' },
    ],
    testimonial: { quote: 'The leadership program completely changed how I show up for my team. My reports now come to me with ideas instead of problems. That shift alone was worth everything.', name: 'Vikram Nair', role: 'Engineering Manager, Hyderabad', avatar: IMAGES.avatar2 },
  },

  softSkills: {
    slug: 'softSkills',
    title: 'Soft Skills Training',
    tagline: 'The people skills that accelerate every career, no matter the field.',
    category: 'Flagship Program',
    color: '#9b68c4',
    glyph: '⬡',
    heroImg: IMAGES.softSkills,
    galleryImgs: [IMAGES.heroStudents, IMAGES.blog3, IMAGES.teamCollab],
    duration: '4 Weeks',
    format: 'Online / Offline — Group',
    level: 'Students & Early-career',
    language: 'English, Hindi, Marathi',
    overview: [
      'Technical skills get you the interview. Soft skills get you the job — and every promotion after. This intensive 4-week program builds the interpersonal and professional competencies that employers consistently rank as their top requirements.',
      'Designed for students entering the job market and early-career professionals, the program covers communication, teamwork, time management, problem-solving, and adaptability through live workshops and real-world scenarios.',
    ],
    outcomes: [
      'Communicate professionally in emails, meetings, and presentations',
      'Collaborate effectively in diverse teams',
      'Manage time, priorities, and deadlines with confidence',
      'Think critically and solve problems creatively',
      'Adapt gracefully to change and ambiguity',
      'Build a professional reputation that stands out',
    ],
    curriculum: [
      { module: 'Week 1: Communication & Presence', topics: ['Professional email writing', 'Meeting etiquette', 'Non-verbal communication'] },
      { module: 'Week 2: Teamwork & Collaboration', topics: ['Understanding team roles', 'Giving and receiving feedback', 'Cross-cultural communication'] },
      { module: 'Week 3: Problem-Solving & Creativity', topics: ['Design thinking basics', 'Root cause analysis', 'Creative brainstorming'] },
      { module: 'Week 4: Adaptability & Professionalism', topics: ['Growth mindset practices', 'Managing change', 'Building your professional brand'] },
    ],
    whoFor: [
      'Final-year students preparing for placement season',
      'Fresh graduates in their first 1–2 years of work',
      'College students wanting a competitive edge',
      'Anyone who wants to improve workplace relationships',
    ],
    faqs: [
      { q: 'Is this different from the Personality Development program?', a: 'Yes. Soft Skills Training focuses on workplace-specific professional competencies. Personality Development is a deeper personal transformation journey. Many students do both.' },
      { q: 'What is the batch size?', a: 'Groups of 15–25 for maximum interaction and role-play practice.' },
    ],
    testimonial: { quote: 'I thought I just needed technical skills for my job. After this program, I realised soft skills are what actually get things done. My manager noticed the difference within a month.', name: 'Karan Joshi', role: 'Junior Developer, Pune', avatar: IMAGES.avatar1 },
  },

  workshop: {
    slug: 'workshop',
    title: 'Workshop Facilitation',
    tagline: 'Custom-designed transformation experiences for institutions and organisations.',
    category: 'Flagship Program',
    color: '#e05a6e',
    glyph: '▲',
    heroImg: IMAGES.workshop,
    galleryImgs: [IMAGES.aboutHero, IMAGES.blog4, IMAGES.office],
    duration: '1–3 Days',
    format: 'On-site / Online — Custom',
    level: 'All levels',
    language: 'English, Hindi, Marathi',
    overview: [
      'IkigaiE Workshop Facilitation brings our most impactful programs directly to your institution or organisation. Whether you need a one-day team-building experience or a three-day deep-dive for your college\'s student body, we design everything from scratch around your specific goals.',
      'Our facilitators are trained professionals with experience across corporates, colleges, NGOs, and government institutions. Every workshop is energetic, interactive, and produces measurable outcomes.',
    ],
    outcomes: [
      'A fully customised program built around your goals and audience',
      'Interactive, high-energy sessions that people actually remember',
      'Practical takeaways participants can apply immediately',
      'Comprehensive post-workshop report and recommendations',
      'Optional follow-up sessions and ongoing support',
    ],
    curriculum: [
      { module: 'Discovery Phase', topics: ['Stakeholder interviews', 'Goal and outcome definition', 'Audience analysis'] },
      { module: 'Design Phase', topics: ['Custom curriculum development', 'Activity and exercise design', 'Material preparation'] },
      { module: 'Delivery', topics: ['Interactive facilitated sessions', 'Group activities and breakouts', 'Real-time Q&A and coaching'] },
      { module: 'Follow-up', topics: ['Post-workshop report', 'Key takeaways and recommendations', 'Optional continuation plans'] },
    ],
    whoFor: [
      'Colleges and universities for student orientation or placement prep',
      'Corporates needing team building or skill development',
      'NGOs and government bodies seeking community development',
      'Schools looking for student development programs',
    ],
    faqs: [
      { q: 'How far in advance should we book?', a: 'We recommend booking at least 2–3 weeks in advance to allow proper discovery and design. For large events, 4–6 weeks is preferred.' },
      { q: 'What is the minimum group size?', a: 'We work with groups of 20 and above. For smaller groups, our flagship programs are a better fit.' },
      { q: 'Do you travel outside Mumbai?', a: 'Yes. We facilitate workshops across India. Travel and accommodation costs are billed separately.' },
    ],
    testimonial: { quote: 'We had 300 first-year students go through IkigaiE\'s two-day orientation workshop. The energy, the content, the facilitators — absolutely world-class. We\'ve booked them every year since.', name: 'Prof. Aditi Kulkarni', role: 'Dean of Students, Pune University', avatar: IMAGES.avatar3 },
  },

  // ─── SOFTWARE ────────────────────────────────────────────────
  fullstack: {
    slug: 'fullstack',
    title: 'Full Stack Development',
    tagline: 'Build complete web applications from database to browser.',
    category: 'Software Development',
    color: '#3670a8',
    glyph: '⬡',
    heroImg: IMAGES.coding,
    galleryImgs: [IMAGES.blog1, IMAGES.ai, IMAGES.data],
    duration: '16 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Beginner to Intermediate',
    language: 'English, Hindi',
    overview: [
      'Full Stack Development is the most versatile and in-demand tech skill in India\'s booming startup and IT ecosystem. This comprehensive 16-week program takes you from zero to deploying production-ready web applications.',
      'You will master both the frontend (React, HTML, CSS, JavaScript) and backend (Node.js, Express, databases), plus deployment, Git, and professional developer workflows used at top companies.',
    ],
    outcomes: [
      'Build complete web applications independently',
      'Work proficiently with React, Node.js, and SQL/NoSQL databases',
      'Deploy apps to cloud platforms (Vercel, Railway, AWS)',
      'Write clean, maintainable code following industry standards',
      'Build a portfolio of 4+ real projects to show employers',
      'Be job-ready for junior developer roles in India\'s top companies',
    ],
    curriculum: [
      { module: 'Phase 1: Foundations', topics: ['HTML5, CSS3, Flexbox & Grid', 'JavaScript fundamentals', 'Git & version control'] },
      { module: 'Phase 2: Frontend', topics: ['React fundamentals & hooks', 'State management', 'REST API integration'] },
      { module: 'Phase 3: Backend', topics: ['Node.js & Express', 'Database design (PostgreSQL & MongoDB)', 'Authentication & security'] },
      { module: 'Phase 4: Capstone', topics: ['Full-stack project build', 'Deployment & DevOps basics', 'Portfolio & job prep'] },
    ],
    whoFor: ['Career changers entering tech', 'Students wanting job-ready coding skills', 'Entrepreneurs building their own products', 'Developers wanting to go full-stack'],
    faqs: [
      { q: 'Do I need prior coding experience?', a: 'No. The program starts from absolute basics. A laptop and willingness to practice daily is all you need.' },
      { q: 'How many hours per week?', a: 'Expect 15–20 hours per week including live sessions, assignments, and project work.' },
    ],
    testimonial: { quote: 'I went from being a commerce graduate with zero coding knowledge to landing a junior developer role in 5 months. The curriculum is intense but incredibly rewarding.', name: 'Sahil Verma', role: 'Junior Developer, Bangalore', avatar: IMAGES.avatar1 },
  },

  java: {
    slug: 'java',
    title: 'Java Development',
    tagline: 'Master enterprise-grade Java and Spring Boot for backend engineering.',
    category: 'Software Development',
    color: '#e85d20',
    glyph: '◉',
    heroImg: IMAGES.coding,
    galleryImgs: [IMAGES.blog1, IMAGES.data, IMAGES.cloud],
    duration: '14 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Beginner to Intermediate',
    language: 'English, Hindi',
    overview: [
      'Java remains the backbone of enterprise software in India — from banking systems to large-scale web services. This 14-week program builds deep Java expertise covering core Java, object-oriented programming, Spring Boot, and microservices.',
      'You will work on industry-relevant projects and leave job-ready for backend engineering roles at Indian IT companies, product companies, and startups.',
    ],
    outcomes: [
      'Write robust Java applications using OOP principles',
      'Build RESTful APIs with Spring Boot',
      'Design and integrate relational databases with JPA/Hibernate',
      'Understand microservices architecture fundamentals',
      'Write unit and integration tests with JUnit',
      'Be ready for Java backend developer interviews',
    ],
    curriculum: [
      { module: 'Core Java', topics: ['OOP concepts', 'Collections framework', 'Exception handling & I/O'] },
      { module: 'Spring Ecosystem', topics: ['Spring Boot fundamentals', 'REST API development', 'Spring Security'] },
      { module: 'Database Integration', topics: ['JPA & Hibernate', 'MySQL with Spring', 'Query optimisation'] },
      { module: 'Advanced & Project', topics: ['Microservices basics', 'Docker fundamentals', 'Capstone project'] },
    ],
    whoFor: ['Aspiring backend developers', 'IT professionals upskilling for product companies', 'CS students wanting enterprise-level Java skills'],
    faqs: [
      { q: 'Is Java still relevant in 2026?', a: 'Absolutely. Java is the primary language for enterprise banking, insurance, and large-scale backend systems in India and globally. Demand for Java developers remains extremely high.' },
    ],
    testimonial: { quote: 'The Spring Boot modules were exactly what I needed for my TCS interview prep. I cleared the technical round on the first attempt.', name: 'Neha Gaikwad', role: 'Software Engineer, TCS', avatar: IMAGES.avatar3 },
  },

  blockchain: {
    slug: 'blockchain',
    title: 'Blockchain Development',
    tagline: 'Build decentralised applications on Ethereum and Solana.',
    category: 'Software Development',
    color: '#9b68c4',
    glyph: '✦',
    heroImg: IMAGES.coding,
    galleryImgs: [IMAGES.ai, IMAGES.cloud, IMAGES.blog1],
    duration: '10 Weeks',
    format: 'Online — Live',
    level: 'Intermediate',
    language: 'English',
    overview: [
      'Blockchain is reshaping finance, supply chain, and digital ownership. This 10-week program teaches you to build decentralised applications (dApps) on Ethereum and Solana — two of the world\'s leading blockchain platforms.',
      'You will write Solidity smart contracts, build Web3 frontends, and deploy real projects, gaining skills that are in short supply and high demand globally.',
    ],
    outcomes: [
      'Write and deploy smart contracts in Solidity',
      'Build Web3 frontends with React and ethers.js',
      'Understand consensus mechanisms and blockchain architecture',
      'Deploy dApps on Ethereum testnets',
      'Understand NFTs, DeFi, and DAO fundamentals',
    ],
    curriculum: [
      { module: 'Blockchain Fundamentals', topics: ['How blockchain works', 'Ethereum & Solana ecosystem', 'Wallets & transactions'] },
      { module: 'Smart Contracts', topics: ['Solidity basics & advanced', 'Testing with Hardhat', 'Security best practices'] },
      { module: 'Web3 Frontend', topics: ['Connecting React to blockchain', 'ethers.js & wagmi', 'MetaMask integration'] },
      { module: 'Projects & Deployment', topics: ['Build an NFT marketplace', 'Deploy to testnet', 'Portfolio preparation'] },
    ],
    whoFor: ['Developers wanting to enter Web3', 'CS students interested in blockchain careers', 'Professionals looking to transition into crypto/DeFi'],
    faqs: [
      { q: 'Do I need prior blockchain knowledge?', a: 'No blockchain knowledge needed. But you should have basic programming experience (any language).' },
    ],
    testimonial: { quote: 'The smart contracts module alone opened up three freelance opportunities for me on Upwork. Blockchain skills are genuinely rare and well paid.', name: 'Rohan Desai', role: 'Web3 Freelancer', avatar: IMAGES.avatar2 },
  },

  // ─── TECHNOLOGY ──────────────────────────────────────────────
  ai: {
    slug: 'ai',
    title: 'Artificial Intelligence',
    tagline: 'Understand, build and deploy AI systems from the ground up.',
    category: 'Technology',
    color: '#3d8f52',
    glyph: '✦',
    heroImg: IMAGES.ai,
    galleryImgs: [IMAGES.coding, IMAGES.data, IMAGES.cloud],
    duration: '12 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Beginner to Intermediate',
    language: 'English, Hindi',
    overview: [
      'Artificial Intelligence is the defining technology of our era. This 12-week program gives you a thorough foundation in AI concepts, machine learning, neural networks, and natural language processing — with hands-on Python projects throughout.',
      'You will move from understanding how AI works to actually building models, training them on real datasets, and deploying them as usable applications.',
    ],
    outcomes: [
      'Understand core AI and ML concepts with confidence',
      'Build classification, regression, and clustering models',
      'Train neural networks using TensorFlow and Keras',
      'Work with NLP models for text classification and generation',
      'Deploy AI models as APIs and web applications',
      'Be equipped for AI/ML roles in India\'s booming tech industry',
    ],
    curriculum: [
      { module: 'AI Foundations', topics: ['History & types of AI', 'Python for AI (NumPy, Pandas)', 'Data preprocessing & visualisation'] },
      { module: 'Machine Learning', topics: ['Supervised & unsupervised learning', 'Scikit-learn models', 'Model evaluation & tuning'] },
      { module: 'Deep Learning', topics: ['Neural network architecture', 'TensorFlow & Keras', 'CNNs for image recognition'] },
      { module: 'NLP & Deployment', topics: ['Text processing & transformers', 'Building a chatbot', 'Deploying models with FastAPI'] },
    ],
    whoFor: ['Students wanting AI/ML careers', 'Data analysts moving into AI', 'Developers wanting to add AI to their skillset', 'Business professionals needing AI literacy'],
    faqs: [
      { q: 'Do I need a math background?', a: 'Basic understanding of statistics and linear algebra helps but we cover the essential concepts from scratch within the program.' },
    ],
    testimonial: { quote: 'I built my first image classifier in week 6. By week 12 I had deployed a working NLP app. The pace is challenging but the mentors are exceptional.', name: 'Aditya Kulkarni', role: 'ML Engineer (fresher)', avatar: IMAGES.avatar1 },
  },

  ml: {
    slug: 'ml',
    title: 'Machine Learning',
    tagline: 'Master the algorithms powering modern AI with Python and real datasets.',
    category: 'Technology',
    color: '#3670a8',
    glyph: '◆',
    heroImg: IMAGES.data,
    galleryImgs: [IMAGES.ai, IMAGES.coding, IMAGES.blog1],
    duration: '10 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Intermediate',
    language: 'English, Hindi',
    overview: [
      'Machine Learning is the engine behind recommendation systems, fraud detection, predictive analytics, and hundreds of other applications shaping modern business. This 10-week program builds deep, practical ML expertise.',
      'Every module is grounded in real datasets and real problems, ensuring you graduate with a portfolio of ML projects rather than just theory.',
    ],
    outcomes: [
      'Implement all major ML algorithms from scratch and with libraries',
      'Perform feature engineering and data preprocessing at a professional level',
      'Evaluate, tune, and optimise ML models rigorously',
      'Work with Scikit-learn, XGBoost, and Pandas confidently',
      'Build end-to-end ML pipelines',
    ],
    curriculum: [
      { module: 'Foundations', topics: ['Statistics for ML', 'Data cleaning & EDA', 'Train/test splits & cross-validation'] },
      { module: 'Supervised Learning', topics: ['Linear & logistic regression', 'Decision trees & random forests', 'SVM & KNN'] },
      { module: 'Unsupervised Learning', topics: ['K-means clustering', 'Dimensionality reduction (PCA)', 'Anomaly detection'] },
      { module: 'Advanced Topics', topics: ['Ensemble methods & boosting', 'Feature selection & engineering', 'ML project deployment'] },
    ],
    whoFor: ['Data analysts wanting to add ML skills', 'Software developers moving into AI', 'Students targeting data science roles'],
    faqs: [
      { q: 'Is Python knowledge required?', a: 'Yes — basic Python proficiency is required. We recommend completing our Python with AI course first if you are a beginner.' },
    ],
    testimonial: { quote: 'The feature engineering week alone made me significantly better at my job. I started applying these techniques immediately and my model accuracy improved by 18%.', name: 'Divya Menon', role: 'Data Analyst, Bangalore', avatar: IMAGES.avatar3 },
  },

  python: {
    slug: 'python',
    title: 'Python with AI',
    tagline: 'Learn Python from scratch and apply it in real AI projects.',
    category: 'Technology',
    color: '#c9a84c',
    glyph: '◉',
    heroImg: IMAGES.coding,
    galleryImgs: [IMAGES.ai, IMAGES.data, IMAGES.blog1],
    duration: '8 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Absolute Beginner',
    language: 'English, Hindi, Marathi',
    overview: [
      'Python is the world\'s most popular programming language — and the primary language of AI and data science. This beginner-friendly 8-week program teaches you Python from scratch and immediately applies it to real AI and data projects.',
      'By the end, you will have solid Python foundations and practical experience with NumPy, Pandas, Matplotlib, and basic TensorFlow — making you ready to progress to our ML or AI courses.',
    ],
    outcomes: [
      'Write clean, efficient Python code with confidence',
      'Use Python for data manipulation with Pandas and NumPy',
      'Visualise data with Matplotlib and Seaborn',
      'Build simple ML models with Scikit-learn',
      'Understand how AI libraries like TensorFlow work',
    ],
    curriculum: [
      { module: 'Python Basics', topics: ['Variables, data types, loops', 'Functions & modules', 'File handling & error management'] },
      { module: 'Data with Python', topics: ['NumPy arrays', 'Pandas DataFrames', 'Data cleaning & transformation'] },
      { module: 'Visualisation', topics: ['Matplotlib & Seaborn charts', 'Exploratory data analysis', 'Communicating insights visually'] },
      { module: 'AI Introduction', topics: ['Scikit-learn basics', 'Your first ML model', 'Introduction to TensorFlow'] },
    ],
    whoFor: ['Complete coding beginners', 'Non-tech professionals wanting Python literacy', 'Students wanting an accessible entry into AI'],
    faqs: [
      { q: 'Is this the same as a general Python course?', a: 'No — we focus specifically on Python for data and AI, not web or software development, to keep the learning path focused and immediately applicable.' },
    ],
    testimonial: { quote: 'I was a marketing manager with zero coding experience. After 8 weeks I was writing Python scripts to automate my reports. It genuinely changed my workflow.', name: 'Sneha Patil', role: 'Marketing Manager, Mumbai', avatar: IMAGES.avatar1 },
  },

  excel: {
    slug: 'excel',
    title: 'Advanced Excel',
    tagline: 'From spreadsheets to business intelligence — master Excel at a professional level.',
    category: 'Technology',
    color: '#27ae60',
    glyph: '★',
    heroImg: IMAGES.data,
    galleryImgs: [IMAGES.blog2, IMAGES.blog1, IMAGES.office],
    duration: '5 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Beginner to Advanced',
    language: 'English, Hindi, Marathi',
    overview: [
      'Excel is used by over 1 billion people — yet most use less than 10% of its power. This program teaches you to use Excel like a financial analyst, transforming raw data into meaningful business insights in minutes.',
      'From VLOOKUP and pivot tables to Power Query, Power BI integration, and macro automation, every skill covered is directly applicable to real-world business scenarios.',
    ],
    outcomes: [
      'Build dynamic dashboards and reports executives actually read',
      'Master VLOOKUP, INDEX-MATCH, SUMIFS and advanced formulas',
      'Automate repetitive tasks with macros and basic VBA',
      'Use Power Query to clean and transform messy data',
      'Create professional pivot tables and pivot charts',
    ],
    curriculum: [
      { module: 'Core Excel', topics: ['Essential formulas & functions', 'Data validation & conditional formatting', 'Sorting, filtering & tables'] },
      { module: 'Advanced Formulas', topics: ['VLOOKUP & XLOOKUP', 'INDEX-MATCH', 'Array formulas & dynamic ranges'] },
      { module: 'Pivot Tables & Charts', topics: ['Building pivot reports', 'Calculated fields', 'Dashboard design principles'] },
      { module: 'Power Tools & Automation', topics: ['Power Query data transformation', 'Macro recording & VBA basics', 'Power BI integration'] },
    ],
    whoFor: ['Finance, HR, and operations professionals', 'Students wanting Excel proficiency for placements', 'Anyone who spends hours doing manually what Excel can automate'],
    faqs: [
      { q: 'Which version of Excel do I need?', a: 'Microsoft Excel 2019 or Microsoft 365 (recommended). We cover features available in both.' },
    ],
    testimonial: { quote: 'I used to spend 4 hours building monthly reports. Now it takes 20 minutes with the Power Query workflow I learned here. My manager thinks I\'m a wizard.', name: 'Amit Sharma', role: 'Finance Analyst, Delhi', avatar: IMAGES.avatar2 },
  },

  datascience: {
    slug: 'datascience',
    title: 'Data Science',
    tagline: 'Turn raw data into business decisions — end to end.',
    category: 'Technology',
    color: '#d4521a',
    glyph: '▲',
    heroImg: IMAGES.data,
    galleryImgs: [IMAGES.ai, IMAGES.coding, IMAGES.blog2],
    duration: '14 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Intermediate',
    language: 'English, Hindi',
    overview: [
      'Data Science is the most sought-after profession in India\'s technology sector. This 14-week comprehensive program covers the entire data science lifecycle — from collecting and cleaning data, to building models, to communicating insights to business stakeholders.',
      'You will master Python, SQL, statistics, machine learning, and data visualisation, graduating with a portfolio of end-to-end data science projects.',
    ],
    outcomes: [
      'Work with the full data science workflow end to end',
      'Use Python (Pandas, NumPy, Scikit-learn) and SQL fluently',
      'Apply statistical reasoning to real business problems',
      'Build and deploy predictive models',
      'Create compelling dashboards with Power BI and Tableau',
      'Be interview-ready for data science and analytics roles',
    ],
    curriculum: [
      { module: 'Foundations', topics: ['Python & SQL essentials', 'Statistics & probability', 'Exploratory data analysis'] },
      { module: 'Machine Learning', topics: ['Supervised & unsupervised models', 'Feature engineering', 'Model evaluation'] },
      { module: 'Visualisation & BI', topics: ['Tableau & Power BI', 'Storytelling with data', 'Executive dashboards'] },
      { module: 'Capstone', topics: ['End-to-end data science project', 'Presentation to mock panel', 'Job search strategy'] },
    ],
    whoFor: ['Professionals wanting to move into data science', 'Students targeting analytics roles at top firms', 'Business analysts wanting technical depth'],
    faqs: [
      { q: 'What salary can I expect after this course?', a: 'Entry-level data science roles in India typically range from ₹6–12 LPA, with experienced professionals earning significantly more.' },
    ],
    testimonial: { quote: 'I came from an economics background and was intimidated by the technical content. The mentors made every concept approachable. I got placed at a fintech company 2 months after graduating.', name: 'Anjali Rao', role: 'Data Scientist, Fintech Startup', avatar: IMAGES.avatar3 },
  },

  cyber: {
    slug: 'cyber',
    title: 'Cyber Security',
    tagline: 'Learn to protect systems, networks, and data from modern threats.',
    category: 'Technology',
    color: '#e74c3c',
    glyph: '⬡',
    heroImg: IMAGES.coding,
    galleryImgs: [IMAGES.cloud, IMAGES.blog1, IMAGES.ai],
    duration: '12 Weeks',
    format: 'Online — Live',
    level: 'Intermediate',
    language: 'English',
    overview: [
      'With cybercrime costing the global economy trillions annually, cyber security professionals are among the most in-demand workers in technology. This 12-week program covers network security, ethical hacking, penetration testing, and security frameworks.',
      'All techniques are taught ethically and legally, with dedicated practice labs using safe, isolated environments.',
    ],
    outcomes: [
      'Understand how attackers think and operate',
      'Perform ethical penetration testing on networks and web apps',
      'Implement security best practices across systems',
      'Work with firewalls, IDS/IPS, and SIEM tools',
      'Understand compliance frameworks (ISO 27001, GDPR)',
      'Prepare for CEH and CompTIA Security+ certifications',
    ],
    curriculum: [
      { module: 'Foundations', topics: ['Networking fundamentals', 'Linux for security', 'Cryptography basics'] },
      { module: 'Ethical Hacking', topics: ['Reconnaissance & scanning', 'Exploitation techniques', 'Web application attacks'] },
      { module: 'Defence & Response', topics: ['Firewalls & IDS setup', 'Incident response', 'SIEM & log analysis'] },
      { module: 'Compliance & Capstone', topics: ['Security frameworks overview', 'Penetration test report writing', 'Certification prep'] },
    ],
    whoFor: ['IT professionals wanting to specialise in security', 'Students targeting cybersecurity careers', 'System administrators strengthening their skills'],
    faqs: [
      { q: 'Is ethical hacking legal to learn?', a: 'Yes, completely. Our labs use isolated environments and we cover the legal and ethical framework thoroughly in week one.' },
    ],
    testimonial: { quote: 'The hands-on labs made all the difference. I wasn\'t just reading about SQL injection — I was doing it in a controlled environment, which made it stick permanently.', name: 'Sameer Khan', role: 'Security Analyst, Delhi', avatar: IMAGES.avatar2 },
  },

  cloud: {
    slug: 'cloud',
    title: 'Cloud Computing (AWS & Azure)',
    tagline: 'Architect, deploy and manage solutions on the world\'s leading cloud platforms.',
    category: 'Technology',
    color: '#3670a8',
    glyph: '◎',
    heroImg: IMAGES.cloud,
    galleryImgs: [IMAGES.coding, IMAGES.ai, IMAGES.office],
    duration: '10 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Intermediate',
    language: 'English, Hindi',
    overview: [
      'Cloud computing is no longer the future — it is the present. This 10-week program covers both AWS and Azure, giving you practical, vendor-agnostic cloud skills that are applicable across the entire industry.',
      'You will design architectures, provision infrastructure, manage containers, and understand pricing and security — gaining skills directly needed for cloud engineer and DevOps roles.',
    ],
    outcomes: [
      'Architect cloud solutions on both AWS and Azure',
      'Provision and manage VMs, storage, and networking',
      'Work with containers (Docker) and Kubernetes basics',
      'Implement cloud security and access management',
      'Prepare for AWS Cloud Practitioner and Azure Fundamentals certifications',
    ],
    curriculum: [
      { module: 'Cloud Fundamentals', topics: ['Cloud models & services', 'AWS & Azure architecture', 'Pricing & cost management'] },
      { module: 'Core Services', topics: ['Compute (EC2, Azure VMs)', 'Storage (S3, Blob Storage)', 'Networking (VPC, VNet)'] },
      { module: 'DevOps & Containers', topics: ['CI/CD pipelines', 'Docker & container management', 'Kubernetes introduction'] },
      { module: 'Security & Capstone', topics: ['IAM & access control', 'Cloud security best practices', 'Architecture design project'] },
    ],
    whoFor: ['IT professionals seeking cloud roles', 'Developers wanting cloud deployment skills', 'Students targeting DevOps and cloud engineering careers'],
    faqs: [
      { q: 'Do I need a cloud account?', a: 'Yes. You will need an AWS free tier account and an Azure free account. Both are free to create and we guide you through setup in week one.' },
    ],
    testimonial: { quote: 'I passed both my AWS Cloud Practitioner and Azure Fundamentals exams within 3 months of completing this course. The practical labs prepared me better than any study guide.', name: 'Ritesh Mehta', role: 'Cloud Engineer, Infosys', avatar: IMAGES.avatar1 },
  },

  // ─── MICROSOFT ───────────────────────────────────────────────
  azure: {
    slug: 'azure',
    title: 'Microsoft Azure Fundamentals (AZ-900)',
    tagline: 'Earn your first Microsoft certification with confidence.',
    category: 'Microsoft Certifications',
    color: '#0078d4',
    glyph: '◆',
    heroImg: IMAGES.cloud,
    galleryImgs: [IMAGES.coding, IMAGES.blog1, IMAGES.office],
    duration: '4 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Beginner',
    language: 'English, Hindi',
    badge: 'Certification Prep',
    overview: [
      'The Microsoft Azure Fundamentals (AZ-900) certification is the ideal starting point for anyone entering the cloud industry. This focused 4-week program prepares you fully for the exam while giving you practical cloud literacy.',
      'Structured exactly around the official Microsoft exam objectives, this course ensures you understand cloud concepts, Azure services, pricing, and compliance — and can pass the exam on your first attempt.',
    ],
    outcomes: [
      'Understand core cloud computing concepts and terminology',
      'Navigate and use Azure services with confidence',
      'Understand Azure pricing, SLAs, and support options',
      'Pass the AZ-900 certification exam on your first attempt',
      'Build a strong foundation for advanced Azure certifications (AZ-104, AZ-204)',
    ],
    curriculum: [
      { module: 'Cloud Concepts (25–30%)', topics: ['Cloud computing models', 'CapEx vs OpEx', 'Cloud benefits & types'] },
      { module: 'Azure Architecture (35–40%)', topics: ['Core Azure services', 'Azure compute & storage', 'Azure networking'] },
      { module: 'Security & Compliance (25–30%)', topics: ['Azure security tools', 'Identity & access management', 'Compliance & privacy'] },
      { module: 'Pricing & Exam Prep', topics: ['Azure pricing calculator', '3 full mock exams', 'Exam strategy & tips'] },
    ],
    whoFor: ['Anyone wanting their first cloud certification', 'IT professionals adding cloud credentials', 'Students strengthening their resume for tech roles'],
    faqs: [
      { q: 'What is the exam fee?', a: 'The AZ-900 exam costs approximately ₹4,500. Our course fee does not include the exam voucher, but we help you register and prepare.' },
      { q: 'What is the pass rate for your students?', a: 'Over 90% of our students pass on their first attempt, compared to the global average of around 70%.' },
    ],
    testimonial: { quote: 'Cleared AZ-900 on my first try with a score of 880/1000. The mock exams were almost identical to the real thing. Highly recommended.', name: 'Tanvi Joshi', role: 'IT Support Engineer, Mumbai', avatar: IMAGES.avatar3 },
  },

  // ─── BUSINESS ────────────────────────────────────────────────
  marketing: {
    slug: 'marketing',
    title: 'Digital Marketing',
    tagline: 'Master the complete digital marketing toolkit and drive real results.',
    category: 'Business & Management',
    color: '#d4521a',
    glyph: '✦',
    heroImg: IMAGES.data,
    galleryImgs: [IMAGES.blog2, IMAGES.office, IMAGES.blog5],
    duration: '8 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Beginner to Intermediate',
    language: 'English, Hindi',
    overview: [
      'Digital marketing is one of the fastest-growing and most versatile career fields in India. Whether you want to work at an agency, build a brand, or grow your own business, this 8-week program gives you the complete toolkit.',
      'From SEO and Google Ads to social media strategy, email marketing, and analytics — every module is built around real campaigns, real data, and real results.',
    ],
    outcomes: [
      'Run profitable Google Ads and Meta Ads campaigns',
      'Optimise websites for search engines (SEO)',
      'Build and execute social media content strategies',
      'Design and send high-converting email campaigns',
      'Use Google Analytics 4 to measure and improve performance',
      'Build a digital marketing portfolio for job applications',
    ],
    curriculum: [
      { module: 'Foundations', topics: ['Digital marketing landscape', 'Building buyer personas', 'Setting up Google Analytics'] },
      { module: 'Search & Paid', topics: ['SEO fundamentals', 'Google Ads (Search & Display)', 'Meta Ads Manager'] },
      { module: 'Social & Content', topics: ['Instagram & LinkedIn strategy', 'Content calendar creation', 'Video marketing basics'] },
      { module: 'Email & Analytics', topics: ['Email marketing with Mailchimp', 'Campaign performance analysis', 'Portfolio & career prep'] },
    ],
    whoFor: ['Students wanting a digital marketing career', 'Business owners wanting to grow their brand online', 'Marketing professionals updating their skills'],
    faqs: [
      { q: 'Will I get hands-on experience running real campaigns?', a: 'Yes. You will run real campaigns with a small budget on Google Ads and Meta Ads as part of the coursework.' },
    ],
    testimonial: { quote: 'I came in knowing only Instagram. I left understanding the full marketing funnel and running Google Ads profitably for my family\'s business.', name: 'Pooja Nair', role: 'Digital Marketing Executive', avatar: IMAGES.avatar1 },
  },

  analytics: {
    slug: 'analytics',
    title: 'Data Analytics',
    tagline: 'Transform business data into decisions that matter.',
    category: 'Business & Management',
    color: '#3670a8',
    glyph: '◆',
    heroImg: IMAGES.data,
    galleryImgs: [IMAGES.blog2, IMAGES.coding, IMAGES.office],
    duration: '8 Weeks',
    format: 'Online — Live + Recorded',
    level: 'Beginner to Intermediate',
    language: 'English, Hindi, Marathi',
    overview: [
      'Data analytics is the bridge between raw numbers and business strategy. This 8-week program teaches you to collect, clean, analyse, and visualise data using Excel, SQL, Python, and Power BI — the exact tools used by analysts at top Indian companies.',
    ],
    outcomes: [
      'Query and manipulate databases with SQL confidently',
      'Use Python (Pandas) for data analysis',
      'Build executive dashboards in Power BI',
      'Apply statistical techniques to business data',
      'Communicate data insights to non-technical stakeholders',
    ],
    curriculum: [
      { module: 'Excel & SQL', topics: ['Advanced Excel for analytics', 'SQL fundamentals & joins', 'Database querying'] },
      { module: 'Python Analytics', topics: ['Pandas for data wrangling', 'Statistical analysis', 'Data visualisation with Seaborn'] },
      { module: 'Power BI', topics: ['Building reports & dashboards', 'DAX formulas', 'Publishing & sharing'] },
      { module: 'Capstone', topics: ['End-to-end analytics project', 'Insight presentation', 'Portfolio building'] },
    ],
    whoFor: ['Business professionals wanting data skills', 'Students targeting analyst roles', 'Managers needing to understand data better'],
    faqs: [
      { q: 'Which tools will I need?', a: 'Excel (Microsoft 365), Power BI Desktop (free), and Python (free). SQL is practiced online using free tools.' },
    ],
    testimonial: { quote: 'Before this course I was presenting spreadsheets. Now I present interactive Power BI dashboards. My boss gave me a raise specifically because of this skill.', name: 'Rahul Gupta', role: 'Business Analyst, FMCG Company', avatar: IMAGES.avatar2 },
  },

  leadership_mgmt: {
    slug: 'leadership_mgmt',
    title: 'Leadership & Management Programs',
    tagline: 'Build the leadership skills that get people promoted and companies to grow.',
    category: 'Business & Management',
    color: '#c9a84c',
    glyph: '★',
    heroImg: IMAGES.leadership,
    galleryImgs: [IMAGES.aboutHero, IMAGES.office, IMAGES.blog3],
    duration: '6 Weeks',
    format: 'Online / Offline — Group',
    level: 'Mid-level & above',
    language: 'English, Hindi',
    overview: [
      'This program is designed for working professionals who are ready to step up from individual contributor to leader — or from manager to strategic leader. Drawing from global leadership frameworks and Indian organisational contexts, every module is immediately applicable.',
    ],
    outcomes: [
      'Lead teams with clarity, empathy, and accountability',
      'Navigate organisational politics professionally',
      'Drive performance through coaching rather than commanding',
      'Communicate strategy in a way teams actually follow',
      'Manage up, down, and sideways with confidence',
    ],
    curriculum: [
      { module: 'Leadership Foundations', topics: ['Leadership styles assessment', 'The manager-to-leader shift', 'Building trust quickly'] },
      { module: 'Managing Performance', topics: ['Goal setting & OKRs', 'Performance conversations', 'Coaching vs. directing'] },
      { module: 'Strategic Communication', topics: ['Communicating vision clearly', 'Stakeholder management', 'Influencing without authority'] },
      { module: 'Organisational Effectiveness', topics: ['Change management', 'Building a high-performance culture', 'Your leadership development plan'] },
    ],
    whoFor: ['Senior executives & department heads', 'Mid-level managers ready to lead teams', 'HR teams developing future leaders'],
    faqs: [
      { q: 'Is this the same as the Leadership & Team Building flagship?', a: 'This program is more management-focused and targets experienced professionals. The flagship program is broader and suitable for students and early-career leaders.' },
    ],
    testimonial: { quote: 'I had been a senior individual contributor for 6 years and was terrified of managing people. This program gave me the exact playbook I needed to lead confidently from day one.', name: 'Nisha Krishnamurthy', role: 'Senior Manager, Tech Company', avatar: IMAGES.avatar3 },
  },

  sixsigma: {
    slug: 'sixsigma',
    title: 'Six Sigma',
    tagline: 'Earn your Green Belt and lead data-driven process improvement.',
    category: 'Business & Management',
    color: '#27ae60',
    glyph: '◉',
    heroImg: IMAGES.blog2,
    galleryImgs: [IMAGES.data, IMAGES.office, IMAGES.teamCollab],
    duration: '8 Weeks',
    format: 'Online — Live',
    level: 'Intermediate',
    language: 'English, Hindi',
    badge: 'Certification Prep',
    overview: [
      'Six Sigma is the gold standard in process improvement, used by manufacturing, healthcare, banking, and tech companies worldwide. This 8-week program prepares you for the globally recognised Six Sigma Green Belt certification.',
      'You will master the DMAIC methodology, statistical process control, and root cause analysis through real case studies from Indian industries.',
    ],
    outcomes: [
      'Master the DMAIC (Define, Measure, Analyse, Improve, Control) cycle',
      'Apply statistical tools for process analysis',
      'Lead Six Sigma projects within your organisation',
      'Earn the Six Sigma Green Belt certification',
      'Calculate and communicate ROI from process improvements',
    ],
    curriculum: [
      { module: 'Define & Measure', topics: ['Project charter development', 'Voice of Customer (VOC)', 'Process mapping & measurement'] },
      { module: 'Analyse', topics: ['Root cause analysis tools', 'Hypothesis testing', 'Regression basics'] },
      { module: 'Improve & Control', topics: ['Solution design & pilot', 'Control charts & SPC', 'Sustaining improvements'] },
      { module: 'Certification Prep', topics: ['Practice exams', 'Case study reviews', 'Exam registration guidance'] },
    ],
    whoFor: ['Quality and operations professionals', 'Engineers in manufacturing or healthcare', 'Managers wanting process improvement credentials'],
    faqs: [
      { q: 'What certification body do you prepare for?', a: 'We prepare students for certifications from ASQ (American Society for Quality) and IASSC, both globally recognised.' },
    ],
    testimonial: { quote: 'After getting my Green Belt, I led a process improvement project that saved my company ₹40 lakhs annually. The ROI on this course was immediate and massive.', name: 'Rajan Iyer', role: 'Operations Manager, Manufacturing', avatar: IMAGES.avatar1 },
  },

  // ─── LANGUAGE ────────────────────────────────────────────────
  english: {
    slug: 'english',
    title: 'Business English',
    tagline: 'Communicate with clarity, confidence and professionalism in English.',
    category: 'Language & Communication',
    color: '#3670a8',
    glyph: '◆',
    heroImg: IMAGES.speaking,
    galleryImgs: [IMAGES.blog1, IMAGES.heroStudents, IMAGES.blog5],
    duration: '8 Weeks',
    format: 'Online — Live',
    level: 'Beginner to Intermediate',
    language: 'English with Hindi support',
    overview: [
      'In India\'s professional world, English fluency is directly linked to career advancement. This 8-week program focuses specifically on business English — the language of emails, meetings, presentations, negotiations, and the workplace.',
      'With a communicative, confidence-first approach, you will practice speaking, writing, and listening in real business scenarios rather than memorising grammar rules.',
    ],
    outcomes: [
      'Write professional emails, reports, and proposals in English',
      'Participate confidently in English-medium meetings and calls',
      'Deliver clear presentations in English',
      'Handle negotiations and difficult conversations professionally',
      'Expand business vocabulary and eliminate common errors',
    ],
    curriculum: [
      { module: 'Foundations', topics: ['Professional vocabulary building', 'Email writing essentials', 'Grammar for clarity'] },
      { module: 'Spoken English', topics: ['Meeting & call language', 'Presentation delivery', 'Describing work & processes'] },
      { module: 'Advanced Communication', topics: ['Negotiation language', 'Giving & receiving feedback', 'Cross-cultural communication'] },
      { module: 'Polishing', topics: ['Report writing', 'Formal vs. informal register', 'Mock interview in English'] },
    ],
    whoFor: ['Professionals working in English-medium environments', 'Students preparing for corporate interviews', 'Anyone who feels less confident speaking or writing in English'],
    faqs: [
      { q: 'Will sessions be conducted in English or Hindi?', a: 'Sessions are conducted in English, but instructors can clarify concepts in Hindi when needed. The goal is immersive English practice.' },
    ],
    testimonial: { quote: 'My spoken English was a constant source of embarrassment in client meetings. After 8 weeks I was leading those meetings. My confidence went from a 3 to a 9.', name: 'Mohan Das', role: 'Account Manager, IT Services', avatar: IMAGES.avatar2 },
  },

  softSkillsComm: {
    slug: 'softSkillsComm',
    title: 'Soft Skills Training',
    tagline: 'Build the professional competencies that accelerate every career.',
    category: 'Language & Communication',
    color: '#3d8f52',
    glyph: '✦',
    heroImg: IMAGES.softSkills,
    galleryImgs: [IMAGES.heroStudents, IMAGES.teamCollab, IMAGES.blog3],
    duration: '4 Weeks',
    format: 'Online / Offline — Group',
    level: 'All levels',
    language: 'English, Hindi, Marathi',
    overview: [
      'This communication-focused version of our Soft Skills program is designed for teams, institutions, and individuals who need to sharpen professional communication, interpersonal effectiveness, and workplace behaviour.',
    ],
    outcomes: [
      'Communicate clearly and professionally in any work context',
      'Navigate workplace relationships with confidence and empathy',
      'Give and receive constructive feedback effectively',
      'Build a reputation for professionalism and reliability',
    ],
    curriculum: [
      { module: 'Professional Communication', topics: ['Verbal & written clarity', 'Active listening', 'Meeting & email etiquette'] },
      { module: 'Interpersonal Skills', topics: ['Building rapport quickly', 'Navigating conflict', 'Workplace empathy'] },
      { module: 'Teamwork & Collaboration', topics: ['Working across personalities', 'Constructive feedback culture', 'Remote team communication'] },
      { module: 'Professional Presence', topics: ['Personal branding at work', 'Networking in professional settings', 'Managing up & sideways'] },
    ],
    whoFor: ['Corporate teams needing communication training', 'College students entering professional life', 'HR teams onboarding new hires'],
    faqs: [
      { q: 'Is this different from the flagship Soft Skills program?', a: 'This version has a stronger communication and language focus and is popular for corporate group bookings and college placements.' },
    ],
    testimonial: { quote: 'We put our entire graduate trainee batch through this program. The difference in how they communicate with clients within 3 months was remarkable.', name: 'HR Manager', role: 'Leading IT Company, Hyderabad', avatar: IMAGES.avatar3 },
  },

  foreign: {
    slug: 'foreign',
    title: 'Foreign Languages (Spanish, French, German)',
    tagline: 'Open global doors by learning a new language with native-speaking instructors.',
    category: 'Language & Communication',
    color: '#9b68c4',
    glyph: '◉',
    heroImg: IMAGES.heroStudents,
    galleryImgs: [IMAGES.blog5, IMAGES.blog1, IMAGES.speaking],
    duration: '12 Weeks per language',
    format: 'Online — Live',
    level: 'Beginner (A1–A2)',
    language: 'Taught in target language with English support',
    overview: [
      'Whether you are preparing for international studies, a global career, or simply passionate about language and culture, our foreign language programs in Spanish, French, and German take you from zero to conversational A2 level in 12 weeks.',
      'All instructors are native or near-native speakers who bring cultural immersion to every session, not just language mechanics.',
    ],
    outcomes: [
      'Hold basic conversations confidently in your chosen language',
      'Read, write, and understand everyday texts and communications',
      'Understand cultural contexts essential for business and travel',
      'Lay a strong foundation for B1 and beyond',
      'Optionally prepare for DELF, DELE, or Goethe A2 certification exams',
    ],
    curriculum: [
      { module: 'A1: Absolute Beginner', topics: ['Greetings & introductions', 'Numbers, dates, time', 'Basic vocabulary (food, family, places)'] },
      { module: 'A1–A2: Building Blocks', topics: ['Present tense structures', 'Describing people & things', 'Daily routines & activities'] },
      { module: 'A2: Communication', topics: ['Shopping, travel & directions', 'Past & future basics', 'Short conversations & roleplay'] },
      { module: 'A2: Consolidation', topics: ['Reading & listening exercises', 'Writing short paragraphs', 'Optional certification prep'] },
    ],
    whoFor: ['Students applying to European universities', 'Professionals in global companies', 'Travel enthusiasts and cultural learners', 'Anyone who always wanted to learn a new language'],
    faqs: [
      { q: 'Can I learn two languages simultaneously?', a: 'We recommend focusing on one language at a time for maximum retention, especially at the beginner level.' },
      { q: 'Which language is most useful for Indian professionals?', a: 'French has the most utility for Indian professionals due to its role in African markets, European business, and UPSC aspirants. Spanish is growing rapidly for US-adjacent roles.' },
    ],
    testimonial: { quote: 'I started Spanish to prepare for a work assignment in Colombia. 12 weeks in, I was holding basic conversations with my local colleagues. They were genuinely impressed.', name: 'Arun Krishnan', role: 'Business Development, MNC', avatar: IMAGES.avatar1 },
  },

  ielts: {
    slug: 'ielts',
    title: 'IELTS / TOEFL',
    tagline: 'Achieve your target score and unlock international study and career opportunities.',
    category: 'Language & Communication',
    color: '#9b68c4',
    glyph: '▲',
    heroImg: IMAGES.blog5,
    galleryImgs: [IMAGES.heroStudents, IMAGES.speaking, IMAGES.blog1],
    duration: '8 Weeks',
    format: 'Online — Live',
    level: 'Intermediate to Advanced',
    language: 'English',
    badge: 'Exam Prep',
    overview: [
      'IELTS and TOEFL are gateway exams for studying or working abroad. This 8-week intensive is laser-focused on achieving your target band/score through structured practice, expert feedback, and deep familiarity with the exam format.',
      'We cover all four skills — Listening, Reading, Writing, and Speaking — with dedicated modules for the specific question types and strategies that the examiners look for.',
    ],
    outcomes: [
      'Achieve your target IELTS band (typically 6.5–8.0) or TOEFL score',
      'Master all IELTS question types across all four sections',
      'Write Task 1 and Task 2 essays that score Band 7+',
      'Perform confidently in the IELTS Speaking test',
      'Manage time effectively across all exam sections',
    ],
    curriculum: [
      { module: 'Listening & Reading', topics: ['Question type strategies', 'Skimming & scanning techniques', 'Timed practice sets'] },
      { module: 'Writing Task 1', topics: ['Describing charts & graphs', 'Academic report structure', 'Grammar & vocabulary for Task 1'] },
      { module: 'Writing Task 2', topics: ['Essay structures (opinion, discussion, problem)', 'Cohesion & coherence', 'Band 7 vocabulary usage'] },
      { module: 'Speaking & Mock Tests', topics: ['Part 1, 2, 3 strategies', 'Fluency & pronunciation coaching', '3 full mock tests with feedback'] },
    ],
    whoFor: ['Students applying to universities in UK, USA, Canada, Australia', 'Professionals applying for skilled migration visas', 'Anyone needing English proficiency certification'],
    faqs: [
      { q: 'Which exam do you prepare for — IELTS Academic or General?', a: 'We prepare for both. Most of our students take Academic. Please specify when enrolling so we can tailor your materials.' },
      { q: 'What is the average score improvement?', a: 'Students who complete the full 8-week program typically improve by 0.5–1.5 bands compared to their diagnostic test.' },
    ],
    testimonial: { quote: 'I needed a 7.0 for my UK visa. I had scored 6.0 on my own. After this course I scored 7.5. I could not have done it without the Writing and Speaking coaching.', name: 'Shalini Verma', role: 'Nurse, now working in UK', avatar: IMAGES.avatar3 },
  },
};

export const getAllSlugs = () => Object.keys(PROGRAMS);
